kind: pipeline
name: vue-build

steps:
  - name: vue-build-check
    image: node:lts
    commands:
      - make npm-init
      - ./tests/vue-build.sh

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
